name: Node.js CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      APP_NAME: ${{ secrets.APP_NAME }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run build
        run: npm run build

  deploy-to-railway:
    needs: build-and-test
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service github-actions-express-demo --detach
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}